#!/bin/bash --login
#$ -cwd
#$ -N anyMOD
#$ -o /net/work/goeke/julia/job_log.$JOB_ID.$TASK_ID.out
#$ -j y
#$ -l h_rt=172800
#$ -l mem_free=4G
#$ -pe mp 1
#$ -m bae
#$ -M lgo@wip.tu-berlin.de

qsub -t 2001 -v hours='96' -v hours_heu='96' -v trn='reference' start8_64.job
qsub -t 2002 -v hours='96' -v hours_heu='96' -v trn='avoid' start8_64.job
qsub -t 2003 -v hours='96' -v hours_heu='96' -v trn='shift' start8_64.job





















